server:
  port: 3221
  servlet:
    context-path: /api/poc/batch
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jwt:
    secret: poclaon
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true



  datasource:
    hikari:
      profiles: maria
      jdbc-url: jdbc:mariadb://192.168.100.216:3306/poc_batch?characterEncoding=UTF-8&ServerTimezone=UTC
      username: root
      password: Laonpp00..L
      driver-class-name: org.mariadb.jdbc.Driver